services:
  sistema-ventas:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mvc-sistema-ventas
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      NODE_ENV: production
      DB_PATH: /app/src/database/data/sistema-ventas.db
    volumes:
      - ventas_data:/app/src/database/data
    restart: unless-stopped

volumes:
  ventas_data:
